# themes from https://github.com/alacritty/alacritty-theme

import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]

[font]
size = 18

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
#decorations = "none"
option_as_alt = "Both"

[window.padding]
x = 8
y = 2
