#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config layout bsp

#yabai -m config external_bar off:40:0
#yabai -m config menubar_opacity 1.0

yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autofocus

yabai -m config window_shadow on

#yabai -m config active_window_opacity 1.0
#yabai -m config normal_window_opacity 0.90

yabai -m config display_arrangement_order default
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_zoom_persist on
#yabai -m config window_shadow on
#yabai -m config window_opacity_duration 0.0
#yabai -m config window_opacity off

yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config split_ratio 0.50
yabai -m config split_type auto
yabai -m config auto_balance off

yabai -m config top_padding 3
yabai -m config bottom_padding 3
yabai -m config left_padding 3
yabai -m config right_padding 3
yabai -m config window_gap 3

yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

yabai -m rule --add app="^系統設定$" manage=off
yabai -m rule --add app="^活動監視器$" manage=off
yabai -m rule --add app="^LINE$" manage=off

#yabai -m config menubar_opacity 0.0

# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
yabai -m config external_bar main:30:0
# add 20 padding to the top and bottom of all spaces regardless of the display it belongs to
yabai -m config external_bar all:30:5

echo "yabai configuration loaded.."
borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=3.0 &
